### ISSUE TITLE
Tried dash2.5，seem like only one page can be registered

### ISSUE THREAD

**Issue by sylvoslee** [plotly/dash-labs#111]

**Comment by AnnMarieW** [comment]
Hi @sylvoslee 

Converting from a the dash-labs `pages` plug-in to the `pages` feature in dash 2.5 requires 3 steps:

- remove `import dash_labs as dl`  or upgrade dash-labs to V1.1.0
There is a conflict between dash-labs versions less than 1.1.0 when running a pages app in dash 2.5

- change: 
`app = Dash(__name__, plugins=[dl.plugins.pages])`
to:
`app = Dash(__name__, use_pages=True)`

- change:
`dl.plugins.page_container` 
to:
`dash.page_container`


Let me know how it goes!  The new dash docs with the pages feature will be ready soon.

**Comment by sylvoslee** [comment]
![image](https://user-images.githubusercontent.com/34852097/173297094-78706a00-91de-4b87-8062-04aa0f0cd048.png)

**Comment by AnnMarieW** [comment]
Hi @sylvoslee.  Thanks for reporting.  There is an issue with `pages` in dash 2.5 for for anyone on Windows.  There is a [pull request](https://github.com/plotly/dash/pull/2090) to fix this - patch is coming soon.

**Comment by AnnMarieW** [comment]
@sylvoslee dash 2.5.1 has been released :confetti_ball:

**Comment by sylvoslee** [comment]
another question, how to get the hash value of the url

**Comment by AnnMarieW** [comment]
You can use the  hash prop of dcc.Location

**Comment by sylvoslee** [comment]
Why can't  pass hash value to layout function like query?
```
def layout(day=days[0], **other_unknown_query_strings):
    return html.Div(
        [
            dcc.Dropdown(
                id="dropdown",
                options=[{"label": x, "value": x} for x in days],
                value=day,
                clearable=False,
            ),
            dcc.Graph(id="bar-chart"),
        ]
    )
```
