### ISSUE TITLE
Redirect from '/' results in exception

### ISSUE THREAD

**Issue by brian-cawley** [plotly/dash-labs#114]
### Sample Code:
`dash.register_page(__name__, path='/test', redirect_from=['/'])`

Results in exception 

> AssertionError: View function mapping is overwriting an existing endpoint function: /

**Comment by AnnMarieW** [comment]
Yes, that's correct - you can't redirect from the rood directory.  

Instead you can do this: 

dash.register_page(__name__, path='/', redirect_from=['/test'])
