### ISSUE TITLE
issue on dash_table(presentation : dropdown) when using mantine provider on mantine>=0.15.0 and flask compability before_first_requests

### ISSUE THREAD

**Issue by kyoshizzz** [plotly/dash-labs#117]
when using dash_mantine_components>=0.15.0,  i cannot use dash_table presentation dropdown anymore when i render it using multipage layout.

when i inspect the element, when the 

`.Select is focused`

the class of 
`.Select-menu-outer`  appearing with `display:none;`

![Image](https://github.com/user-attachments/assets/b9dfac6f-a17b-4fee-9b40-a61513378646)

**Comment by alexcjohnson** [comment]
@kyoshizzz this repo is not currently in use for anything. You'll have better luck posting this at https://github.com/snehilvj/dash-mantine-components if you believe that's where the issue originates. (There's also a mention of `before_first_request` in your title but I don't see anything about that in the text?)

If you make a new issue over there, please include a standalone app that we can copy and run, showing both the broken and working cases. Thanks!
