### ISSUE TITLE
Rename tpl.layout to children and remove "full" kwarg

### ISSUE THREAD

**Issue by jonmmease** [plotly/dash-labs#16]
After some internal discussion, we've tentatively decided to rename the `tpl.layout()` method to a `tpl.children` `@property` to better emphasize that it's possible to include the output of a template in a larger app (e.g. to make it the children property of a Div).

Along with that, we think it's best to remove the functionality of the `full` keyword argument to `tpl.layout`.  This argument currently defaults to `True`, and it has the effect of automatically wrapping the template output in a `dbc.Container` (for the dbc templates) or `ddk.App` (for the DDK templates).

This is convenient for simple apps, but it's a bit of magic that could easily trip people up when trying to use templates as part of a larger app (e.g. ending up with multiple `ddk.App` instances.  The cost of removing this functionality is that the user would need to import the corresponding toolkit library and wrap the template result in the appropriate app container.  The advantage here is that we think it will make it a lot more clear what the template is actually producing, and how to integrate a template result with a larger app, or how to create an app that consists of multiple templates (e.g. a separate template per tab).

cc @chriddyp @nicolaskruchten @alexcjohnson @AnnMarieW

**Comment by jonmmease** [comment]
Ok, I forgot that `tpl.layout(app)` also includes the app as an argument. This is needed because currently this is the point where custom stylesheets are applied.

We might be able to move the app to the template constructor to get around this... I'll chew on it.

**Comment by AnnMarieW** [comment]
In my Theme Explorer app, I update the stylesheet with a clientside callback.  Do you that could work here too?

**Comment by jonmmease** [comment]
Yeah, I think that could be an alternative to setting the stylesheet on the app. But either way, we need a way for the template to get direct access to the app at some point. Keeping in mind that you can use a template without passing it to `app.callback` so we can't rely on performing the association there.
