### ISSUE TITLE
[Idea] Support `dl.Input(object.arg)` format

### ISSUE THREAD

**Issue by xhlulu** [plotly/dash-labs#18]
Currently we would do:
```python
import dash_labs as dl
...
div = html.Div()
button = html.Button(children="Click Me")

@app.callback(dl.Output(div, "children"), dl.Input(button, "n_clicks"))
def callback(n_clicks):
    return "Clicked {} times".format(n_clicks)
```

I feel being able to input the argument directly would be more type-ahead friendly, the Python interpreter will throw an error right away if the argument doesn't exist, and it looks slightly more consistent too.
```python
import dash_labs as dl
...
div = html.Div()
button = html.Button(children="Click Me")

@app.callback(dl.Output(div.children), dl.Input(button.n_clicks))
def callback(n_clicks):
    return "Clicked {} times".format(n_clicks)
```

Not sure if this is feasible without changing the component structure though (since the arguments are assigned to a value so there's no way to retrace the id of the actual object).

**Comment by jonmmease** [comment]
The trouble is that `div.chidren` already evaluates to the component property value.  In an earlier iteration I introduced a special syntax for this `div.props["children"]`, but folks felt like it was too confusing.

**Comment by xhlulu** [comment]
> The trouble is that `div.chidren` already evaluates to the component property value. In an earlier iteration I introduced a special syntax for this `div.props["children"]`, but folks felt like it was too confusing.

Yeah that's a very difficult problem. I wonder if `div.input.n_clicks` could return `dl.Input(div, "n_clicks")` - but in this scenario it might not support typehead which is the main benefit :/ 

I briefly thought about how we could make `div.n_clicks` a `PropObject` where `__repr__` returns the string ID (not sure how that would work for patterns). However that would make things more complicated for end users trying to access the value of a component outside a callback so doesn't seem realistic.
