### ISSUE TITLE
dash-labs not support python 3.8 yet?

### ISSUE THREAD

**Issue by zjuzhfbloodz** [plotly/dash-labs#28]
I've run some dash-labs examples and get error called
>   File "/Users/bytedance/opt/anaconda3/lib/python3.8/multiprocessing/reduction.py", line 60, in dump
>    ForkingPickler(file, protocol).dump(obj)
>AttributeError: Can't pickle local object 'make_update_cache.<locals>._callback'

My version is 
python 3.8.5
dash 1.20.0
dash-bootstrap-components 0.12.2

**Comment by sebbegg** [comment]
Seeing the same issue with 

- python 3.9.6
- dash==1.21.0
- dash-labs==0.4.0

**Comment by sebbegg** [comment]
FYI - the workaround mentioned here worked for me:
https://github.com/tarantool/test-run/issues/265
